language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
group: stable

before_install: ./CI/before_install.${TRAVIS_OS_NAME}.sh

install: ./CI/before_install.${TRAVIS_OS_NAME}.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
