language: cpp
sudo: required
dist: trusty
os: linux
compiler: gcc
group: stable

before_install:    
- sudo apt-get install libsdl2-dev
- sudo apt-get install libsdl2-image-dev
- sudo apt-get install libopenal-dev
- sudo apt-get install opencl-headers
- sudo apt-get install ocl-icd-libopencl1
- wget https://github.com/KhronosGroup/OpenCL-CLHPP/releases/download/v2.0.10/cl2.hpp
- sudo mv cl2.hpp /usr/include/CL/
- sudo apt-get install wildmidi

script:
- mkdir build
- cd build
- cmake ..
- make
